name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore PolySharpFeatureTests.sln

      - name: Build Solution
        run: |
          msbuild.exe PolySharpFeatureTests.sln /p:platform="Any CPU" /p:configuration="Release" /p:AllowUnsafeBlocks=true
        
      - name: Run Tests
        run: |
          vstest.console.exe CSharp8.Tests\bin\Release\CSharp8.Tests.dll CSharp9.Tests\bin\Release\CSharp9.Tests.dll CSharp10.Tests\bin\Release\CSharp10.Tests.dll /parallel
