name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore PolySharpFeatureTests.sln

      - name: Build Solution
        run: msbuild.exe PolySharpFeatureTests.sln /p:platform="Any CPU" /p:configuration="Release" /p:AllowUnsafeBlocks=true

      - name: Run C# 8 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net45\CSharp8.Tests.dll

      - name: Run C# 8 4.5.1 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net451\CSharp8.Tests.dll 

      - name: Run C# 8 4.5.2 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net452\CSharp8.Tests.dll

      - name: Run C# 8 4.6 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net46\CSharp8.Tests.dll

      - name: Run C# 8 4.6.1 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net461\CSharp8.Tests.dll

      - name: Run C# 8 4.6.2 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net462\CSharp8.Tests.dll

      - name: Run C# 8 4.7 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net47\CSharp8.Tests.dll

      - name: Run C# 8 4.7.1 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net471\CSharp8.Tests.dll

      - name: Run C# 8 4.7.2 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net472\CSharp8.Tests.dll

      - name: Run C# 8 4.8 Tests
        run: vstest.console.exe CSharp8.Tests\bin\Release\net48\CSharp8.Tests.dll

      - name: Run C# 9 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net45\CSharp9.Tests.dll

      - name: Run C# 9 4.5.1 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net451\CSharp9.Tests.dll 

      - name: Run C# 9 4.5.2 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net452\CSharp9.Tests.dll

      - name: Run C# 9 4.6 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net46\CSharp9.Tests.dll

      - name: Run C# 9 4.6.1 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net461\CSharp9.Tests.dll

      - name: Run C# 9 4.6.2 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net462\CSharp9.Tests.dll

      - name: Run C# 9 4.7 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net47\CSharp9.Tests.dll

      - name: Run C# 9 4.7.1 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net471\CSharp9.Tests.dll

      - name: Run C# 9 4.7.2 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net472\CSharp9.Tests.dll

      - name: Run C# 9 4.8 Tests
        run: vstest.console.exe CSharp9.Tests\bin\Release\net48\CSharp9.Tests.dll

      - name: Run C# 10 4.5 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net45\CSharp10.Tests.dll 

      - name: Run C# 10 4.5.1 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net451\CSharp10.Tests.dll 

      - name: Run C# 10 4.5.2 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net452\CSharp10.Tests.dll

      - name: Run C# 10 4.6 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net46\CSharp10.Tests.dll

      - name: Run C# 10 4.6.1 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net461\CSharp10.Tests.dll

      - name: Run C# 10 4.6.2 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net462\CSharp10.Tests.dll

      - name: Run C# 10 4.7 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net47\CSharp10.Tests.dll

      - name: Run C# 10 4.7.1 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net471\CSharp10.Tests.dll

      - name: Run C# 10 4.7.2 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net472\CSharp10.Tests.dll

      - name: Run C# 10 4.8 Tests
        run: vstest.console.exe CSharp10.Tests\bin\Release\net48\CSharp10.Tests.dll
