name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore PolySharpFeatureTests.sln

      - name: Build Solution
        run: |
          msbuild.exe PolySharpFeatureTests.sln /p:platform="Any CPU" /p:configuration="Release" /p:AllowUnsafeBlocks=true

      - name: Run C# 8 Tests
        run: |
          vstest.console.exe CSharp8.Tests\bin\Release\CSharp8.Tests.dll /parallel

      - name: Run C# 9 Tests
        run: |
          vstest.console.exe CSharp9.Tests\bin\Release\CSharp9.Tests.dll /parallel

      - name: Run C# 10 Tests
        run: |
          vstest.console.exe CSharp10.Tests\bin\Release\net451\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net452\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net46\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net461\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net462\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net47\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net471\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net472\CSharp10.Tests.dll |
          vstest.console.exe CSharp10.Tests\bin\Release\net48\CSharp10.Tests.dll /parallel
